### ISSUE TITLE
Detokenization doesn't work as expected

### ISSUE THREAD

**Issue by jacqle** [psawa/gecko-app#10]
Current behavior: the TreebankWordDetokenizer fails to group back together hyphenated words.
Expected behavior: the output text does not contain any additional spaces compared to the input text.
E.g.:  _An out-of-the-box feature_ ->  _An out - of - the - box feature_

**Comment by jacqle** [comment]
One possible fix would be to add an ad hoc regex.

**Comment by Eduardo-Calo** [comment]
> 
> 
> One possible fix would be to add an ad hoc regex.

yes, that could work. I think it's the quickest thing we can do.
