### ISSUE TITLE
Add DEMO BUTTON

### ISSUE THREAD

**Issue by Eduardo-Calo** [psawa/gecko-app#12]
Add a demo button with the sentence of the recipes to show all the functionalities.

**Comment by thiborose** [comment]
Add a sentence above the boxes, in beige: What kind of errors it can correct. plus the button at the end of the sentence.

The sentence and button should fade on typing. and be back when boxes are empty

**Comment by thiborose** [comment]
The demo functionality is working. It is triggered by pressing ctrl+d. 

To add demo sentences, just add them in the list in demo.js. 

Now I will add a button.

**Comment by thiborose** [comment]
I added a demo area containing a demo button and a small sentence, which explains what the tool can do. 

When something is typed in the input box, this demo area fades out. And when the box becomes back empty, this area fades in. 


 Don't hesitate to reopen if you see possible improvements.

**Comment by thiborose** [comment]
Pb: It doesn't fade on paste
