### ISSUE TITLE
Pasting text in non-empty input box

### ISSUE THREAD

**Issue by jacqle** [psawa/gecko-app#15]
Not sure what is causing this, but I've noticed two related bugs:

- When selecting a text to paste something over it, the selected text remains and the pasted text is added at the end.
- When selecting a place in the text to paste, the pasted text is added at the end too.

**Comment by thiborose** [comment]
Absolutely, these bugs were introduced when I made the functionality to remove the formatting on paste, in #6. I couldn't find a solution that would avoid the bugs you mentioned.

**Comment by thiborose** [comment]
just removed the changes made for #6 
https://github.com/psawa/gecko-app/commit/5ce9fe49d404edc24924084a58a319f9d2875b62
