### ISSUE TITLE
Don't find "pysdb" "0.3.4"

### ISSUE THREAD

**Issue by MariasStory** [psawa/gecko-app#27]
During the docker build there was an arror that the "pysdb==0.3.4" is not found.
I got it running by changed the version to "pysdb==0.0.3".

The docker build brocke on:
/bin/sh: 1: cd: can't cd to application/models/gector/data/model_files

Please fix the issues.
Even better, please upload the docker file to hub.docker.com

**Comment by MariasStory** [comment]
The last modification of the pysdb version did not help:
```
ModuleNotFoundError: No module named 'pysbd'
The command '/bin/sh -c python -c "from application.models.gector import model; model = model.load_model(vocab_path = 'application/models/gector/data/output_vocabulary',model_paths = ['application/models/gector/data/model_files/xlnet_0_gector.th'],model_name = 'xlnet')"' returned a non-zero code: 1
```

**Comment by MariasStory** [comment]
Thank for pointing me to your docker file.

```
sudo docker pull nlpmasternancy/gecko
Using default tag: latest
Error response from daemon: manifest for nlpmasternancy/gecko:latest not found: manifest unknown: manifest unknown
```

**Comment by thiborose** [comment]
> Thank for pointing me to your docker file.
> 
> ```
> sudo docker pull nlpmasternancy/gecko
> Using default tag: latest
> Error response from daemon: manifest for nlpmasternancy/gecko:latest not found: manifest unknown: manifest unknown
> ```

For this, it is because you didn't specify the image tag. Currently the latest tag is 1, so the correct command is `sudo docker pull nlpmasternancy/gecko:1`. 

We'll investigate further for the errors related to pysdb, for now I don't know I've never had this problem.
