### ISSUE TITLE
Towards a sentence reordering model 

### ISSUE THREAD

**Issue by thiborose** [psawa/gecko-app#3]
https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering

https://paperswithcode.com/task/sentence-ordering

Try to implement a sentence reordering model in addition to the grammar corrector

**Comment by Eduardo-Calo** [comment]
I've been investigating the model and it's a bit cumbersome. I have a step-by-step guidelines file to replicate everything done so far. The results are difficult to interpret and the format strange. I'll take a closer look (also at the issue on their page).

**Comment by Eduardo-Calo** [comment]
The pipeline is ready!!! Whenever you want we can start implementing it.

**Comment by psawa** [comment]
Sure ! let's go for it. Please don't forget to branch before pushing.

**Comment by thiborose** [comment]
The pipeline has been implemented! Now some things need to be fixed before merging: 

- [x] The model is loaded at each query, so it is very slow (~10s per query)
- [x] The tags in the output box are not displayed properly. This is because the delta function compares the input text and output text after the reordering. When sentences are swapped, it considers full sentences as replaced.
- [x] The model file must be ignored (too heavy), and downloaded automatically via setup.sh (http://tts.speech.cs.cmu.edu/sentence_order/nips_bert.tar)

**Comment by thiborose** [comment]
The sentence reordering model has been successfully implemented! 

Now, we still have to avoid loading the model at each query, which makes it very slow.  I'll work on this.

**Comment by thiborose** [comment]
Now the model is loaded once as mentioned. It improved the reordering time from far: now it's **around ~4s.** It's still too long, but I that will do the job for now.... 

Eventually what could be done, is let users choose if they want to use this sentence reordering model, via a toggle button in the interface. 

Don't hesitate to reopen if you have an idea on how to improve that!
