### ISSUE TITLE
sentence_order model link is broken

### ISSUE THREAD

**Issue by ShaidaMuhammad** [psawa/gecko-app#30]
The link is broken. 
http://tts.speech.cs.cmu.edu/sentence_order/nips_bert.tar 
can't download the nips_bert.tar model while running the following command

`mkdir -p application/models/sentence_reorder && cd application/models/sentence_reorder/ && curl -O http://tts.speech.cs.cmu.edu/sentence_order/nips_bert.tar && tar -xf nips_bert.tar && rm nips_bert.tar && mv nips_bert/ model/`

**Comment by thiborose** [comment]
Thanks for reporting. However, the link isn't broken on my side. Maybe it was a temporary sort of thing

**Comment by ShaidaMuhammad** [comment]
> Thanks for reporting. However, the link isn't broken on my side. Maybe it was a temporary sort of thing

This link was fixed after a few days as I have reported it via email as well.
