### ISSUE TITLE
words  been truncated during correction

### ISSUE THREAD

**Issue by DivyaKanniah** [psawa/gecko-app#31]
. Hi we are using your code for GEC but we could see below sentence been corrected even though its correct

'Inpatients and Outpatients are allowed ' been modified as 'patients and patients..Could you please look on this

**Comment by thiborose** [comment]
We did no train the GEC model.  We used a pretrained version of Gector, (https://github.com/grammarly/gector). Our contribution was limited to web-interface it,  and to pipe it with another ML model (https://arxiv.org/abs/2005.00432). 
Good luck with your challenge.
