### ISSUE TITLE
General UX improvements

### ISSUE THREAD

**Issue by thiborose** [psawa/gecko-app#6]
We have various UX improvement to make, suggested by some students in cognitive science: 

- [x] Set key bindings to trigger correction by typing enter, and go back to line by typing shift+enter

- [x] Check the quality of our profile descriptions. (Edu: "at Samsung", Leo: ", and", Thi: "which, I am convinced, can")

- [x] Change the About part adding the discourse feature description and citing the other model we'll implement

**Comment by Eduardo-Calo** [comment]
What do you think of adding an example sentence placeholder on the left box, when one opens the website? Like we could put the very first example on discourse fallacy we used on the slides, in addition to the tagline.

**Comment by thiborose** [comment]
I think it would be annoying if a text has to be removed from the input box each time the page is loaded. Having a use case example of how to use the tool is a great idea though

**Comment by thiborose** [comment]
I reverted the changes regarding the formatting, it was generating more problems than it could solve some.

https://github.com/psawa/gecko-app/commit/5ce9fe49d404edc24924084a58a319f9d2875b62
