### ISSUE TITLE
Process the input text sentence by sentence

### ISSUE THREAD

**Issue by thiborose** [psawa/gecko-app#7]
Current behaviour: I don't know exactly why, but if you want to correct several sentences, in some cases punctuation will be removed after correction. 

Expected behaviour: 
The input text should be processed sentence by sentence, and punctuation should remain when needed.

**Comment by jacqle** [comment]
Indeed, I was able to replicate this bug. One thing that's related and that we have to deal with too is the untokenization of multiple sentences. Currently you end up with a space before a full stop (e.g. ... stretched **.** If ...).

**Comment by jacqle** [comment]
I was able to fix both of these bugs using proper segmentation with spacy (see delta_function branch).

**Comment by thiborose** [comment]
Bug spotted: When a dot is added at the end of the sentence, the last token is tagged as REPLACE even if the token in itself hasn't been modified. 
![image](https://user-images.githubusercontent.com/38402230/101805039-929aca00-3b12-11eb-88dd-9e1236fee037.png)
